# From https://sgoel.dev/posts/uploading-binary-wheels-to-pypi-from-github-actions/

name: wheels 
on: [push]
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup pip
        run: |
           python -m pip install --upgrade pip
           pip install --upgrade cython
           pip install --upgrade numpy
           pip install cibuildwheel==1.6.4

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-*

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
